### ISSUE TITLE
Luca's todo list

### ISSUE THREAD

**Issue by z3ntu** [MadeInSpengergasse/Honeypot#5]
- [ ] Server side validation of pretty much everything
- [ ] Fix suggestions
- [x] Breadcrumb navigation with "angular-crumble" (need dynamic parent)
- [x] Fix labels for navigation
- [x] Remove crumb label when on home page (debug!)
- [x] Modal confirm dialog for "Remove" buttons
- [ ] Edit functionality for everything (UI needs to get updated first @Xorok !)
- [x] WSGI for apache
- [x] Fix modal fullscreens only working the second time
- [x] Dynamic title attribute
- [x] Remove "home" from navigation
- [x] Remove milestone is broken.
