### ISSUE TITLE
Adrian's todo list

### ISSUE THREAD

**Issue by Xorok** [MadeInSpengergasse/Honeypot#7]
- [ ] Fix "add todo" modal (you removed some of the neccessary css, eg for asignee)
- [ ] Fix all other modals
- [ ] ng-href instead of ng-click with own method (might not be the best idea actually)
- [ ] Internet Explorer compatibility
- [x] Fix zoom on mobile
- [x] Fix margins on mobile
- [ ] Redesign most pages
- [ ] Prettify "no items in list" messages

**Comment by z3ntu** [comment]
:angry: :smile:
